---

version: 2
jobs:

  gomplate_tests:
    docker:
    - image: hairyhenderson/gomplate:v3.2.0-alpine
    resource_class: medium
    working_directory: ~/scale-network/tests/unit/openwrt
    steps:
    - checkout:
        path: ~/scale-network

    - run:
        name: install diffutils
        command: apk update && apk add diffutils

    # Netgear WNDR 3700v2, 3800, 3800ch configs
    - run:
        name: openwrt ar71xx golden file test
        command: sh -x test.sh -t ar71xx

    # TP-Link c2600 configs
    - run:
        name: openwrt ipq806x golden file test
        command: sh -x test.sh -t ipq806x

  # This build takes a long time and should be done
  # outside of initial PR CI testing
  openwrt_build_ar71xx:
    docker:
      - image: sarcasticadmin/openwrt-build@sha256:e744706323d34bd51f8abc0a9d0413c4a53817c09b6ab50666acafe66eaefb38
    resource_class: medium
    working_directory: ~/scale-network/openwrt
    steps:
      - checkout:
          path: ~/scale-network

      - run:
          name: build openwrt image
          command: TARGET=ar71xx make templates build-img

      - run:
          name: copy ar71xx artifacts
          command: |
              mkdir -p /tmp/ar71xx
              cp /home/openwrt/scale-network/openwrt/build/source-ar71xx-*/bin/targets/ar71xx/generic/*factory.img /tmp/ar71xx
              cp /home/openwrt/scale-network/openwrt/build/source-ar71xx-*/bin/targets/ar71xx/generic/sha256sums /tmp/ar71xx

      - store_artifacts:
          path: /tmp/ar71xx

  openwrt_build_ipq806x:
    docker:
      - image: sarcasticadmin/openwrt-build@sha256:e744706323d34bd51f8abc0a9d0413c4a53817c09b6ab50666acafe66eaefb38
    resource_class: medium
    working_directory: ~/scale-network/openwrt
    steps:
      - checkout:
          path: ~/scale-network

      - run:
          name: build openwrt image
          command: TARGET=ipq806x make templates build-img

      - run:
          name: copy ipq806x artifacts
          command: |
              mkdir -p /tmp/ipq806x
              cp /home/openwrt/scale-network/openwrt/build/source-ipq806x-*/bin/targets/ipq806x/generic/*factory.bin /tmp/ipq806x
              cp /home/openwrt/scale-network/openwrt/build/source-ipq806x-*/bin/targets/ipq806x/generic/sha256sums /tmp/ipq806x

      - store_artifacts:
          path: /tmp/ipq806x

  ansible_lint:
    docker:
    - image: circleci/python:3.7.2-node-browsers-legacy
    resource_class: medium
    working_directory: ~/scale-network/ansible
    steps:
    - checkout:
        path: ~/scale-network

    - run:
        name: install ansible-lint
        command: sudo pip install ansible-lint

    - run:
        name: lint scale.yml
        command: ansible-lint -x 503 -x 405 etc/ansible/scale.yml

    - run:
        name: install pylint
        command: sudo pip install pylint

    - run:
        name: lint inventory.py
        command: pylint inventory.py --confidence=HIGH

    - run:
        name: test inventory.py
        command: ./inventory.py | jq

  perl_lint:
    docker:
    - image: perl:5
    resource_class: medium
    working_directory: ~/scale-network
    steps:
    - checkout:
        path: ~/scale-network

    - run:
        name: compile switch-configuration
        # Make all warnings into errors so perl has a return thats not 0
        command: find ./switch-configuration/ -iname "*.pl" | xargs -i perl -Mstrict -Mdiagnostics -M'warnings FATAL=>q(all)' -cw {}

    - run:
        name: Set temp password
        # Make sure we set a password
        command: echo "scale" > ./facts/secrets/jroot_pw

    - run:
        name: run switch-configuration
        working_directory: ~/scale-network/switch-configuration/config
        # Make sure we set a password
        command: ./scripts/build_switch_configs.pl

workflows:
  version: 2
  test_all:
    jobs:
      - gomplate_tests
      - ansible_lint
      - perl_lint
  weekly:
    triggers:
      - schedule:
          cron: "15 3 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - openwrt_build_ar71xx
      - openwrt_build_ipq806x
